### ISSUE TITLE
Find a better Messenger bot platform.

### ISSUE THREAD

**Issue by kmchmk** [kmchmk1026/SinhalaAruth#3]
Find a better bot platform.
Better if it can connect to multiple chat platforms.
Add the findings here.
Ex: Cost, simplicity.

**Comment by janakact** [comment]
Options. 
1. Bot Press: (Stars: 8k)  https://github.com/botpress/botpress
2. Ana (Stars: 181) https://github.com/nowfloats/ProjectAna
3. RasaHQ (Stars: 9k,)Not sure whether this will work.:  https://github.com/RasaHQ/rasa
4. Microsoft Bot Framework. (Stars: 6k) https://github.com/microsoft/botframework-sdk

Did you find anything else ?

**Comment by janakact** [comment]
@kmchmk1026 :)
